"""
FastAPI backend for Open-Journal: /chat and /end-session.
"""
from __future__ import annotations

import asyncio
import os
import uuid
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# Load .env from project root first (parent of backend/), then cwd
_root = Path(__file__).resolve().parent.parent
for name in (".env", ".env.local"):
    load_dotenv(_root / name)
    load_dotenv(Path.cwd() / name)
    load_dotenv(Path.cwd().parent / name)

from graph import build_graph, build_librarian_graph, JournalState
from langchain_core.messages import HumanMessage
from library import (
    COLLECTION_EPISODIC,
    COLLECTION_GIST,
    _get_chroma,
    add_consumed,
    generate_memory_mermaid,
    generate_recommendations,
    get_memory_for_visualization,
    save_session_data,
    wipe_memory,
)

# In-memory session store (minimal for 1hr sprint; replace with Redis/DB later)
sessions: dict[str, list] = {}

CHAT_INVOKE_TIMEOUT_SEC = 60


def get_or_create_session(session_id: Optional[str]) -> str:
    if not session_id:
        session_id = str(uuid.uuid4())
    if session_id not in sessions:
        sessions[session_id] = []
    return session_id


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup: log whether env is loaded (no secrets)
    key = os.getenv("OPENROUTER_API_KEY")
    if key and key.strip():
        print("[backend] OPENROUTER_API_KEY is set (ready for /chat)")
    else:
        print("[backend] WARNING: OPENROUTER_API_KEY is missing. Set it in .env at project root and restart.")
    yield
    # Cleanup if needed
    pass


app = FastAPI(title="Open-Journal Backend", lifespan=lifespan)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

chat_graph = build_graph()
librarian_graph = build_librarian_graph()


class ChatRequest(BaseModel):
    text: str
    session_id: Optional[str] = None
    personalization: Optional[float] = None
    intrusiveness: Optional[float] = None


class ChatResponse(BaseModel):
    response: str
    session_id: str
    retrieval_log: Optional[str] = None


class EndSessionRequest(BaseModel):
    session_id: str


class EndSessionResponse(BaseModel):
    ok: bool
    session_id: str


class IngestHistoryRequest(BaseModel):
    text: str
    session_id: Optional[str] = None


class IngestHistoryResponse(BaseModel):
    ok: bool
    session_id: str


class InferEntryDateRequest(BaseModel):
    text: str


class InferEntryDateResponse(BaseModel):
    date: Optional[str] = None  # ISO 8601 or null if unclear


class MemoryStats(BaseModel):
    gist_facts_count: int
    episodic_log_count: int


class RecommendationItem(BaseModel):
    title: str
    author: str = ""
    reason: str = ""
    url: str = ""


class RecommendationsResponse(BaseModel):
    books: list[RecommendationItem]
    podcasts: list[RecommendationItem]
    articles: list[RecommendationItem]
    research: list[RecommendationItem]


class ConsumedRequest(BaseModel):
    type: str  # "book" | "podcast" | "article"
    title: str
    author: Optional[str] = None
    url: Optional[str] = None
    liked: bool = True


class ConsumedResponse(BaseModel):
    ok: bool


class MemoryDiagramResponse(BaseModel):
    mermaid: str


@app.get("/memory-diagram", response_model=MemoryDiagramResponse)
async def memory_diagram():
    """
    Return a Mermaid diagram string generated by LLM from vector DB content (gist facts + episodic summaries).
    """
    gist_facts, episodic_summaries = get_memory_for_visualization()
    mermaid_code = generate_memory_mermaid(gist_facts, episodic_summaries)
    return MemoryDiagramResponse(mermaid=mermaid_code)


@app.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest):
    """User sends text; Interviewer responds. State updated in memory."""
    session_id = get_or_create_session(req.session_id)
    messages = sessions[session_id]

    # Clamp personalization between 0 and 1.0, default to 1.0 if missing.
    personalization = req.personalization if req.personalization is not None else 1.0
    try:
        personalization = float(personalization)
    except (TypeError, ValueError):
        personalization = 1.0
    personalization = max(0.0, min(1.0, personalization))

    # Clamp intrusiveness between 0 and 1.0, default to 0.5 if missing.
    intrusiveness = req.intrusiveness if req.intrusiveness is not None else 0.5
    try:
        intrusiveness = float(intrusiveness)
    except (TypeError, ValueError):
        intrusiveness = 0.5
    intrusiveness = max(0.0, min(1.0, intrusiveness))

    # Append user message
    messages.append(HumanMessage(content=req.text))

    # Run Interviewer in a thread so we don't block the event loop; timeout to avoid hanging
    state: JournalState = {
        "messages": list(messages),
        "session_id": session_id,
        "personalization": personalization,
        "intrusiveness": intrusiveness,
    }
    try:
        result = await asyncio.wait_for(
            asyncio.to_thread(chat_graph.invoke, state),
            timeout=CHAT_INVOKE_TIMEOUT_SEC,
        )
    except asyncio.TimeoutError:
        messages.pop()
        print("[backend] /chat timed out after %ss" % CHAT_INVOKE_TIMEOUT_SEC)
        from fastapi import HTTPException
        raise HTTPException(
            status_code=504,
            detail=f"Chat took longer than {CHAT_INVOKE_TIMEOUT_SEC}s (LLM or memory slow). Try again or lower personalization.",
        )

    # Persist updated messages
    sessions[session_id] = list(result["messages"])

    # Last message is the assistant reply
    last = result["messages"][-1]
    response_text = getattr(last, "content", str(last))
    if isinstance(response_text, list):
        response_text = " ".join(
            c.get("text", str(c)) for c in response_text if isinstance(c, dict)
        )
    retrieval_log = result.get("retrieval_log")

    return ChatResponse(response=response_text, session_id=session_id, retrieval_log=retrieval_log)


@app.post("/end-session", response_model=EndSessionResponse)
async def end_session(req: EndSessionRequest):
    """Trigger Librarian: extract, embed, save to ChromaDB."""
    session_id = get_or_create_session(req.session_id)
    messages = sessions.get(session_id, [])

    state: JournalState = {
        "messages": messages,
        "session_id": session_id,
        "personalization": 1.0,
    }
    librarian_graph.invoke(state)

    return EndSessionResponse(ok=True, session_id=session_id)


@app.post("/ingest-history", response_model=IngestHistoryResponse)
async def ingest_history(req: IngestHistoryRequest):
    """
    Ingest a prior journal text directly into Chroma memory.
    Treats `text` as a single-session transcript.
    """
    session_id = req.session_id or f"import-{uuid.uuid4()}"
    save_session_data(session_id, req.text)
    return IngestHistoryResponse(ok=True, session_id=session_id)


INFER_DATE_SYSTEM = """You are a date extractor. Given journal text, determine the single date and time when this journal entry was written.
The text may mention multiple dates (e.g. past events, "yesterday", "last week"). Choose the date that best represents when the author wrote this entry (e.g. "It is currently January 5, 2026, 1:59 a.m.").
Reply with ONLY a single line: either an ISO 8601 date-time in UTC (e.g. 2026-01-05T01:59:00.000Z), or the word NONE if you cannot determine it. No other text."""


@app.post("/infer-entry-date", response_model=InferEntryDateResponse)
async def infer_entry_date(req: InferEntryDateRequest):
    """
    Use an LLM to infer the best-guess date/time when a journal entry was written.
    Returns ISO 8601 string or null if unclear.
    """
    key = os.getenv("OPENROUTER_API_KEY")
    if not key or not key.strip():
        return InferEntryDateResponse(date=None)
    try:
        from langchain_openai import ChatOpenAI
        from langchain_core.messages import HumanMessage, SystemMessage
        llm = ChatOpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=key,
            model=os.getenv("OPENROUTER_MODEL", "openai/gpt-4o-mini"),
            temperature=0,
        )
        # Truncate very long text to avoid token limits
        text = (req.text or "")[:8000].strip()
        if not text:
            return InferEntryDateResponse(date=None)
        messages = [
            SystemMessage(content=INFER_DATE_SYSTEM),
            HumanMessage(content=text),
        ]
        result = await asyncio.to_thread(llm.invoke, messages)
        raw = getattr(result, "content", str(result))
        if isinstance(raw, list):
            raw = " ".join(c.get("text", str(c)) for c in raw if isinstance(c, dict))
        raw = (raw or "").strip()
        if not raw or raw.upper() == "NONE":
            return InferEntryDateResponse(date=None)
        # Try to parse as ISO; accept if it looks like ISO date
        from datetime import datetime
        iso = raw.split()[0].strip()
        if not iso:
            return InferEntryDateResponse(date=None)
        try:
            dt = datetime.fromisoformat(iso.replace("Z", "+00:00"))
            return InferEntryDateResponse(date=dt.strftime("%Y-%m-%dT%H:%M:%S.000Z"))
        except Exception:
            pass
        for fmt in ("%Y-%m-%dT%H:%M:%S.%fZ", "%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%d"):
            try:
                dt = datetime.strptime(iso[:26], fmt)
                return InferEntryDateResponse(date=dt.strftime("%Y-%m-%dT%H:%M:%S.000Z"))
            except Exception:
                continue
        return InferEntryDateResponse(date=None)
    except Exception as e:
        print("[backend] /infer-entry-date error:", e)
        return InferEntryDateResponse(date=None)


@app.get("/memory-stats", response_model=MemoryStats)
async def memory_stats():
    """
    Lightweight stats endpoint to verify Chroma is populated.
    """
    client = _get_chroma()
    gist = client.get_collection(COLLECTION_GIST)
    episodic = client.get_collection(COLLECTION_EPISODIC)
    return MemoryStats(
        gist_facts_count=gist.count(),
        episodic_log_count=episodic.count(),
    )


@app.get("/recommendations", response_model=RecommendationsResponse)
async def get_recommendations():
    """
    Generate personalized book, podcast, and article recommendations from journal memory
    and what the user has already consumed/liked.
    """
    try:
        data = await asyncio.to_thread(generate_recommendations)
    except Exception as e:
        print("[backend] /recommendations error:", e)
        return RecommendationsResponse(books=[], podcasts=[], articles=[], research=[])
    return RecommendationsResponse(
        books=[RecommendationItem(**x) for x in data.get("books", [])],
        podcasts=[RecommendationItem(**x) for x in data.get("podcasts", [])],
        articles=[RecommendationItem(**x) for x in data.get("articles", [])],
        research=[RecommendationItem(**x) for x in data.get("research", [])],
    )


@app.post("/recommendations/consumed", response_model=ConsumedResponse)
async def mark_consumed(req: ConsumedRequest):
    """
    Record that the user has read/listened to a recommendation. Stored in Chroma
    so future recommendations avoid repeats and better match their tastes.
    """
    content_type = (req.type or "article").lower()
    if content_type not in ("book", "podcast", "article", "research"):
        content_type = "article"
    try:
        add_consumed(
            content_type=content_type,
            title=req.title,
            author=req.author,
            url=req.url,
            liked=req.liked,
        )
        return ConsumedResponse(ok=True)
    except Exception as e:
        print("[backend] /recommendations/consumed error:", e)
        return ConsumedResponse(ok=False)


@app.post("/memory-wipe")
async def memory_wipe():
    """
    Wipe all data from the vector DB (gist_facts and episodic_log). Collections are recreated empty.
    """
    wipe_memory()
    return {"ok": True, "message": "Memory wiped."}


@app.get("/health")
async def health():
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("BACKEND_PORT", "8000"))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=True)
